// <auto-generated />
using System;
using DASHBOARD.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DASHBOARD.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260826165638_RemoveWiki")]
    partial class RemoveWiki
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DASHBOARD.Domain.Entities.BacklogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcceptanceCriteria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Documents")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Rank")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SprintId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int?>("StoryPoints")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("TshirtSize")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("SprintId");

                    b.HasIndex("RepositoryId", "Type", "Rank");

                    b.ToTable("BacklogItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000001"),
                            AcceptanceCriteria = "",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Documents = "[]",
                            Rank = 1000m,
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001"),
                            State = 1,
                            Title = "Authentication & Authorization",
                            TshirtSize = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000002"),
                            AcceptanceCriteria = "Given valid credentials, when I submit the login form, then I am redirected to /overview.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Documents = "[]",
                            ParentId = new Guid("00000000-0000-0000-0008-000000000001"),
                            Rank = 1000m,
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001"),
                            State = 2,
                            StoryPoints = 5,
                            Title = "User can log in with email and password",
                            Type = 2
                        });
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.CapacityMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HoursPerDay")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)");

                    b.Property<decimal>("OvertimeHoursPerDay")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("UserId");

                    b.HasIndex("SprintId", "UserId")
                        .IsUnique();

                    b.ToTable("CapacityMembers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0009-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HoursPerDay = 8m,
                            OvertimeHoursPerDay = 0m,
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001"),
                            Role = "Developer",
                            SprintId = new Guid("00000000-0000-0000-0007-000000000001"),
                            UserId = new Guid("00000000-0000-0000-0001-000000000002")
                        });
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.DayOff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("Hours")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("SprintId");

                    b.HasIndex("UserId");

                    b.ToTable("DaysOff", (string)null);
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.DiscussionEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SprintTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("SprintTaskId");

                    b.ToTable("DiscussionEntries", (string)null);
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.HistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SprintTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("SprintTaskId");

                    b.ToTable("HistoryEntries", (string)null);
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("RoleId");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("IX_Invitations_TokenHash");

                    b.HasIndex("Email", "RepositoryId", "Status")
                        .HasDatabaseName("IX_Invitations_Email_RepositoryId_Status");

                    b.ToTable("Invitations", (string)null);
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LicenseDueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LicenseExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("LicenseRepoCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Alias")
                        .IsUnique();

                    b.HasIndex("LicenseKey")
                        .IsUnique();

                    b.ToTable("Organizations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0009-000000000001"),
                            About = "Default organization created for pre-existing repositories and users.",
                            Alias = "default",
                            ContactEmail = "admin@dashboard.local",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LicenseDueDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            LicenseExpireDate = new DateTime(2027, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            LicenseKey = "TkVYLTAwMDEtUFJPRA==",
                            LicenseRepoCapacity = 20,
                            Name = "Default Organization"
                        });
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsArchived");

                    b.HasIndex("OrgId", "Code")
                        .IsUnique();

                    b.ToTable("Repositories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000001"),
                            Code = "DASH",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Main project repository for the DASHBOARD application.",
                            Name = "Dashboard Project",
                            OrgId = new Guid("00000000-0000-0000-0009-000000000001")
                        });
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.RepositoryMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RepositoryId")
                        .IsUnique();

                    b.ToTable("RepositoryMembers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultRole = "Scrum Master",
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001"),
                            RoleId = new Guid("00000000-0000-0000-0003-000000000010"),
                            UserId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultRole = "Developer",
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001"),
                            RoleId = new Guid("00000000-0000-0000-0003-000000000001"),
                            UserId = new Guid("00000000-0000-0000-0001-000000000002")
                        });
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.RepositoryMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsGlobal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("RepositoryId", "Key")
                        .HasDatabaseName("IX_RepositoryMetadata_RepoId_Key");

                    b.HasIndex("RepositoryId", "Key", "Value")
                        .IsUnique()
                        .HasDatabaseName("UX_RepositoryMetadata_RepoId_Key_Value_Active")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("RepositoryMetadata", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-000b-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsGlobal = false,
                            Key = "RepoRole",
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001"),
                            Value = "Developer"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-000b-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsGlobal = false,
                            Key = "RepoRole",
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001"),
                            Value = "Tester"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-000b-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsGlobal = false,
                            Key = "RepoRole",
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001"),
                            Value = "Scrum Master"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-000b-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsGlobal = false,
                            Key = "RepoRole",
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001"),
                            Value = "Project Manager"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-000b-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsGlobal = false,
                            Key = "RepoRole",
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001"),
                            Value = "Business Analyst"
                        });
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AllowedFunctions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000010"),
                            AllowedFunctions = "[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,16,17,18,19,20]",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full access to all repository functions.",
                            IsDefault = true,
                            Name = "Scrum Master",
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000011"),
                            AllowedFunctions = "[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,16,17,18,19,20]",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manages sprints, capacity, and team settings in addition to all work-item and backlog operations.",
                            IsDefault = true,
                            Name = "Project Manager",
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000012"),
                            AllowedFunctions = "[0,6,7,9,17,18,19]",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Creates and edits sprint tasks, manages the backlog, and can promote items to sprints.",
                            IsDefault = true,
                            Name = "Developer",
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000013"),
                            AllowedFunctions = "[0,6,7,9,10,17]",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Creates and edits sprint tasks and backlog items; focused on quality and test coverage.",
                            IsDefault = true,
                            Name = "Tester",
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000014"),
                            AllowedFunctions = "[0,6,7,8,9,10,11,12,13,17]",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manages the product backlog and requirements; read-only on sprint execution.",
                            IsDefault = true,
                            Name = "Business Analyst",
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000001"),
                            AllowedFunctions = "[0,6,7,9,10,11,12,16,17]",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full work-item and backlog access plus board and sprint management; no member/settings admin.",
                            IsDefault = false,
                            Name = "Senior Developer",
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001")
                        });
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.SmartBoardColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AgingLimitDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MappedState")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WipLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("WipMode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "MappedState");

                    b.HasIndex("RepositoryId", "Order");

                    b.ToTable("SmartBoardColumns", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-000a-000000000001"),
                            AgingLimitDays = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MappedState = 0,
                            Name = "New",
                            Order = 0,
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001"),
                            WipLimit = 0,
                            WipMode = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-000a-000000000002"),
                            AgingLimitDays = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MappedState = 3,
                            Name = "Dev",
                            Order = 1,
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001"),
                            WipLimit = 3,
                            WipMode = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-000a-000000000003"),
                            AgingLimitDays = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MappedState = 4,
                            Name = "In Review",
                            Order = 2,
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001"),
                            WipLimit = 2,
                            WipMode = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-000a-000000000004"),
                            AgingLimitDays = 30,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MappedState = 5,
                            Name = "Done",
                            Order = 3,
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001"),
                            WipLimit = 0,
                            WipMode = 0
                        });
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.Sprint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.ToTable("Sprints", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0007-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateOnly(2026, 5, 15),
                            Name = "Sprint 1 — May 2026",
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001"),
                            StartDate = new DateOnly(2026, 5, 4)
                        });
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.SprintChannelLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HubChannelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HubChannelUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HubChannelId");

                    b.HasIndex("SprintId")
                        .IsUnique();

                    b.ToTable("SprintChannelLinks", (string)null);
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.SprintTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedToId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Automated")
                        .HasColumnType("bit");

                    b.Property<Guid?>("BacklogItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CompletedWork")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("DesignReview")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Environment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Impaction")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("OriginalEstimate")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<decimal>("RemainingWork")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RootCause")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Solution")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("SprintId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StateChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("StepsToReproduce")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StoryPoints")
                        .HasColumnType("int");

                    b.Property<string>("TestSteps")
                        .HasMaxLength(20000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UnitTest")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkItemNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("BacklogItemId");

                    b.HasIndex("ParentId");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("SprintId");

                    b.HasIndex("RepositoryId", "WorkItemNumber")
                        .IsUnique();

                    b.HasIndex("RepositoryId", "Type", "State");

                    b.ToTable("SprintTasks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000002"),
                            AssignedToId = new Guid("00000000-0000-0000-0001-000000000002"),
                            CompletedWork = 0m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Unhandled exception when submitting wrong password.\n\n**Actual:** NullReferenceException on blank page.\n**Expected:** Error message 'Invalid credentials' shown.",
                            DesignReview = "",
                            Environment = "Chrome 124, Windows 11",
                            Impaction = "All users unable to recover from login errors without refreshing.",
                            IsDeleted = false,
                            OriginalEstimate = 0m,
                            Priority = 2,
                            RemainingWork = 0m,
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001"),
                            RootCause = "Missing null-check on auth response before accessing token property.",
                            Solution = "",
                            State = 3,
                            StepsToReproduce = "1. Open /login\n2. Enter wrong password\n3. Click Submit",
                            StoryPoints = 0,
                            Title = "Login page crashes on invalid credentials",
                            Type = 2,
                            UnitTest = "Add test: should display error message when credentials are invalid.",
                            WorkItemNumber = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000005"),
                            AssignedToId = new Guid("00000000-0000-0000-0001-000000000001"),
                            Automated = true,
                            CompletedWork = 0m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Validate the full authentication flow across Chrome, Firefox, and Edge.",
                            IsDeleted = false,
                            OriginalEstimate = 0m,
                            Priority = 1,
                            RemainingWork = 0m,
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001"),
                            State = 0,
                            StoryPoints = 0,
                            TestSteps = "[\"Open /login in Chrome, Firefox, and Edge.\",\"Enter valid credentials and submit.\",\"Verify redirect to /overview and JWT stored in localStorage.\",\"Enter invalid credentials and submit.\",\"Verify error message is displayed without crash.\"]",
                            Title = "End-to-end login flow test plan",
                            Type = 3,
                            WorkItemNumber = 2
                        });
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AuthProvider")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("AvatarClass")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("bg-slate-600");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("GoogleSubjectId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsGlobalAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GoogleSubjectId")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_GoogleSubjectId")
                        .HasFilter("[GoogleSubjectId] IS NOT NULL");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ManagerId");

                    b.HasIndex("OrgId", "Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            AuthProvider = 0,
                            AvatarClass = "bg-sky-600",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@dashboard.local",
                            IsDeleted = false,
                            IsGlobalAdmin = true,
                            Name = "Admin User",
                            OrgId = new Guid("00000000-0000-0000-0009-000000000001"),
                            PasswordHash = "X7gKv4CsinoBoFpwmHYf1N6UWn3XsQZoB0KFQ5fzmkMTANRcm7kbuThFVIEQpx1xb5eT1dGbhTKtWoBpzr0U6A==",
                            PasswordSalt = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            AuthProvider = 0,
                            AvatarClass = "bg-violet-600",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "dev@dashboard.local",
                            IsDeleted = false,
                            IsGlobalAdmin = false,
                            ManagerId = new Guid("00000000-0000-0000-0001-000000000001"),
                            Name = "Dev User",
                            OrgId = new Guid("00000000-0000-0000-0009-000000000001"),
                            PasswordHash = "BF511GUnt57DQ+nwLLCRiKYHFj5nSCXA9RCUwUrV4pDG1WFwJwNMLFM8skh8SafmuxhaXuIgkRNqQjZd7ey6/w==",
                            PasswordSalt = "AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE="
                        });
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.UserToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AccessTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("RefreshTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(88)
                        .HasColumnType("nvarchar(88)");

                    b.Property<bool>("RefreshTokenIsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("RefreshTokenRevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccessTokenExpiresAt");

                    b.HasIndex("JwtId")
                        .IsUnique();

                    b.HasIndex("RefreshTokenExpiresAt");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "JwtId");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.WorkItemMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MetadataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SprintTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MetadataId");

                    b.HasIndex("SprintTaskId", "MetadataId")
                        .IsUnique();

                    b.ToTable("WorkItemMetadata", (string)null);
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.BacklogItem", b =>
                {
                    b.HasOne("DASHBOARD.Domain.Entities.BacklogItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DASHBOARD.Domain.Entities.Sprint", "Sprint")
                        .WithMany()
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Parent");

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.CapacityMember", b =>
                {
                    b.HasOne("DASHBOARD.Domain.Entities.Sprint", "Sprint")
                        .WithMany("CapacityMembers")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DASHBOARD.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sprint");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.DayOff", b =>
                {
                    b.HasOne("DASHBOARD.Domain.Entities.Sprint", "Sprint")
                        .WithMany("DaysOff")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DASHBOARD.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Sprint");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.DiscussionEntry", b =>
                {
                    b.HasOne("DASHBOARD.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DASHBOARD.Domain.Entities.SprintTask", "SprintTask")
                        .WithMany("Discussions")
                        .HasForeignKey("SprintTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("SprintTask");
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.HistoryEntry", b =>
                {
                    b.HasOne("DASHBOARD.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DASHBOARD.Domain.Entities.SprintTask", "SprintTask")
                        .WithMany()
                        .HasForeignKey("SprintTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("SprintTask");
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.Invitation", b =>
                {
                    b.HasOne("DASHBOARD.Domain.Entities.User", "InvitedBy")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DASHBOARD.Domain.Entities.Repository", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DASHBOARD.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("InvitedBy");

                    b.Navigation("Repository");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.Repository", b =>
                {
                    b.HasOne("DASHBOARD.Domain.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.RepositoryMember", b =>
                {
                    b.HasOne("DASHBOARD.Domain.Entities.Repository", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DASHBOARD.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DASHBOARD.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Repository");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.RepositoryMetadata", b =>
                {
                    b.HasOne("DASHBOARD.Domain.Entities.Repository", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.Role", b =>
                {
                    b.HasOne("DASHBOARD.Domain.Entities.Repository", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.SprintChannelLink", b =>
                {
                    b.HasOne("DASHBOARD.Domain.Entities.Sprint", "Sprint")
                        .WithOne()
                        .HasForeignKey("DASHBOARD.Domain.Entities.SprintChannelLink", "SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.SprintTask", b =>
                {
                    b.HasOne("DASHBOARD.Domain.Entities.User", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DASHBOARD.Domain.Entities.BacklogItem", "BacklogItem")
                        .WithMany()
                        .HasForeignKey("BacklogItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DASHBOARD.Domain.Entities.SprintTask", "Parent")
                        .WithMany("SubTasks")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DASHBOARD.Domain.Entities.Sprint", "Sprint")
                        .WithMany("Tasks")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AssignedTo");

                    b.Navigation("BacklogItem");

                    b.Navigation("Parent");

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.User", b =>
                {
                    b.HasOne("DASHBOARD.Domain.Entities.User", "Manager")
                        .WithMany("Subordinates")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DASHBOARD.Domain.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.UserToken", b =>
                {
                    b.HasOne("DASHBOARD.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.WorkItemMetadata", b =>
                {
                    b.HasOne("DASHBOARD.Domain.Entities.RepositoryMetadata", "Metadata")
                        .WithMany()
                        .HasForeignKey("MetadataId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DASHBOARD.Domain.Entities.SprintTask", "SprintTask")
                        .WithMany()
                        .HasForeignKey("SprintTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metadata");

                    b.Navigation("SprintTask");
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.BacklogItem", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.Sprint", b =>
                {
                    b.Navigation("CapacityMembers");

                    b.Navigation("DaysOff");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.SprintTask", b =>
                {
                    b.Navigation("Discussions");

                    b.Navigation("SubTasks");
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.User", b =>
                {
                    b.Navigation("Subordinates");
                });
#pragma warning restore 612, 618
        }
    }
}
