// <auto-generated />
using System;
using DASHBOARD.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DASHBOARD.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260523103658_InitialCreated")]
    partial class InitialCreated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DASHBOARD.Domain.Entities.BacklogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcceptanceCriteria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Documents")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Iteration")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Rank")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int?>("StoryPoints")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("TshirtSize")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("RepositoryId", "Type", "Rank");

                    b.ToTable("BacklogItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000001"),
                            AcceptanceCriteria = "",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Documents = "[]",
                            Rank = 1000m,
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001"),
                            State = 1,
                            Title = "Authentication & Authorization",
                            TshirtSize = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000002"),
                            AcceptanceCriteria = "Given valid credentials, when I submit the login form, then I am redirected to /overview.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Documents = "[]",
                            Iteration = "May 2026",
                            ParentId = new Guid("00000000-0000-0000-0008-000000000001"),
                            Rank = 1000m,
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001"),
                            State = 2,
                            StoryPoints = 5,
                            Title = "User can log in with email and password",
                            Type = 2
                        });
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.CapacityMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HoursPerDay")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)");

                    b.Property<decimal>("OvertimeHoursPerDay")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("UserId");

                    b.HasIndex("SprintId", "UserId")
                        .IsUnique();

                    b.ToTable("CapacityMembers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0009-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HoursPerDay = 8m,
                            OvertimeHoursPerDay = 0m,
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001"),
                            Role = 0,
                            SprintId = new Guid("00000000-0000-0000-0007-000000000001"),
                            UserId = new Guid("00000000-0000-0000-0001-000000000002")
                        });
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.CustomRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AllowedFunctions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.ToTable("CustomRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000001"),
                            AllowedFunctions = "[0,3,4,9,6]",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full access to work items and board; read-only on settings.",
                            Name = "Developer",
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001")
                        });
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.DayOff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("Hours")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("SprintId");

                    b.HasIndex("UserId");

                    b.ToTable("DaysOff", (string)null);
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.DiscussionEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("WorkItemId");

                    b.ToTable("DiscussionEntries", (string)null);
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.HistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("WorkItemId");

                    b.ToTable("HistoryEntries", (string)null);
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("IX_Invitations_TokenHash");

                    b.HasIndex("Email", "RepositoryId", "Status")
                        .HasDatabaseName("IX_Invitations_Email_RepositoryId_Status");

                    b.ToTable("Invitations", (string)null);
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsArchived");

                    b.ToTable("Repositories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000001"),
                            Code = "DASH",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Main project repository for the DASHBOARD application.",
                            Name = "Dashboard Project"
                        });
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.RepositoryMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CustomRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DefaultRole")
                        .HasColumnType("int");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CustomRoleId");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("UserId", "RepositoryId")
                        .IsUnique();

                    b.ToTable("RepositoryMembers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultRole = 2,
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001"),
                            UserId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomRoleId = new Guid("00000000-0000-0000-0003-000000000001"),
                            DefaultRole = 0,
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001"),
                            UserId = new Guid("00000000-0000-0000-0001-000000000002")
                        });
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.RepositoryMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("RepositoryId", "Key")
                        .HasDatabaseName("IX_RepositoryMetadata_RepoId_Key");

                    b.HasIndex("RepositoryId", "Key", "Value")
                        .IsUnique()
                        .HasDatabaseName("UX_RepositoryMetadata_RepoId_Key_Value_Active")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("RepositoryMetadata", (string)null);
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.SmartBoardCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssignedTo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ColumnId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EnteredColumnAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SplitSide")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("SwimlaneId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("WorkItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ColumnId");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("WorkItemId");

                    b.ToTable("SmartBoardCards", (string)null);
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.SmartBoardColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AgingLimitDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MappedState")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Split")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WipLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("WipMode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "Order");

                    b.ToTable("SmartBoardColumns", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-000a-000000000001"),
                            AgingLimitDays = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MappedState = 0,
                            Name = "New",
                            Order = 0,
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001"),
                            Split = false,
                            WipLimit = 0,
                            WipMode = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-000a-000000000002"),
                            AgingLimitDays = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MappedState = 1,
                            Name = "Dev",
                            Order = 1,
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001"),
                            Split = true,
                            WipLimit = 3,
                            WipMode = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-000a-000000000003"),
                            AgingLimitDays = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MappedState = 2,
                            Name = "In Review",
                            Order = 2,
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001"),
                            Split = false,
                            WipLimit = 2,
                            WipMode = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-000a-000000000004"),
                            AgingLimitDays = 30,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MappedState = 3,
                            Name = "Done",
                            Order = 3,
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001"),
                            Split = false,
                            WipLimit = 0,
                            WipMode = 0
                        });
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.Sprint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("RepositoryId", "IsActive");

                    b.ToTable("Sprints", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0007-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateOnly(2026, 5, 15),
                            IsActive = true,
                            Name = "Sprint 1 — May 2026",
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001"),
                            StartDate = new DateOnly(2026, 5, 4)
                        });
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.SprintTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedToId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BacklogItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CompletedWork")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OriginalEstimate")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("RemainingWork")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("StoryPoints")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("BacklogItemId");

                    b.HasIndex("ParentId");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("SprintId");

                    b.ToTable("SprintTasks", (string)null);
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AuthProvider")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("AvatarClass")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("bg-slate-600");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("GoogleSubjectId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsGlobalAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleSubjectId")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_GoogleSubjectId")
                        .HasFilter("[GoogleSubjectId] IS NOT NULL");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ManagerId");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            AuthProvider = 0,
                            AvatarClass = "bg-sky-600",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@dashboard.local",
                            IsDeleted = false,
                            IsGlobalAdmin = true,
                            Name = "Admin User",
                            PasswordHash = "X7gKv4CsinoBoFpwmHYf1N6UWn3XsQZoB0KFQ5fzmkMTANRcm7kbuThFVIEQpx1xb5eT1dGbhTKtWoBpzr0U6A==",
                            PasswordSalt = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            AuthProvider = 0,
                            AvatarClass = "bg-violet-600",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "dev@dashboard.local",
                            IsDeleted = false,
                            IsGlobalAdmin = false,
                            ManagerId = new Guid("00000000-0000-0000-0001-000000000001"),
                            Name = "Dev User",
                            PasswordHash = "BF511GUnt57DQ+nwLLCRiKYHFj5nSCXA9RCUwUrV4pDG1WFwJwNMLFM8skh8SafmuxhaXuIgkRNqQjZd7ey6/w==",
                            PasswordSalt = "AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE="
                        });
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.UserToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AccessTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("RefreshTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(88)
                        .HasColumnType("nvarchar(88)");

                    b.Property<bool>("RefreshTokenIsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("RefreshTokenRevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccessTokenExpiresAt");

                    b.HasIndex("JwtId")
                        .IsUnique();

                    b.HasIndex("RefreshTokenExpiresAt");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "JwtId");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.WikiPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ParentId");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("RepositoryId", "ParentId");

                    b.ToTable("WikiPages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0006-000000000001"),
                            Content = "<h1>Architecture</h1><p>Full-stack .NET 10 + Angular v19 application.</p>",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001"),
                            Title = "System Architecture Overview"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0006-000000000002"),
                            Content = "<h2>Auth</h2><p>JWT Bearer tokens with PBKDF2-SHA512 password hashing.</p>",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ParentId = new Guid("00000000-0000-0000-0006-000000000001"),
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001"),
                            Title = "Authentication Flow"
                        });
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.WorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcceptanceCriteria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("AssignedToId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Automated")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("CompletedWork")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomFieldsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("{}");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("DesignReview")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Environment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FixedInVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Impaction")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImplementInBuild")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Links")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OriginalEstimate")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("RemainingWork")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RootCause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Solution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sprint")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("New");

                    b.Property<string>("StepsToReproduce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StoryPoints")
                        .HasColumnType("int");

                    b.Property<string>("TestSteps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TestSuiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UnitTest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkItemNumber")
                        .HasColumnType("int");

                    b.Property<string>("WorkItemType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("RepositoryId", "WorkItemNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_WorkItems_RepositoryId_WorkItemNumber");

                    b.ToTable("WorkItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000001"),
                            AcceptanceCriteria = "Given valid credentials, when I log in, then I receive a JWT and am redirected to /overview.",
                            AssignedToId = new Guid("00000000-0000-0000-0001-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomFieldsJson = "{}",
                            Description = "Implement JWT-based login flow with token storage.",
                            IsDeleted = false,
                            Links = "[]",
                            Priority = "High",
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001"),
                            Sprint = "May 2026",
                            State = "New",
                            StoryPoints = 5,
                            Title = "As a user, I want to log in with my credentials",
                            WorkItemNumber = 1,
                            WorkItemType = "UserStory"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000002"),
                            AssignedToId = new Guid("00000000-0000-0000-0001-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomFieldsJson = "{}",
                            Description = "Unhandled exception when submitting wrong password.\n\n**Actual:** Application throws NullReferenceException and shows blank page.\n**Expected:** Error message 'Invalid credentials' displayed below the form.",
                            DesignReview = "",
                            Environment = "Chrome 124, Windows 11",
                            Impaction = "All users unable to recover from login errors without refreshing the page.",
                            IsDeleted = false,
                            Links = "[]",
                            Priority = "High",
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001"),
                            RootCause = "Missing null-check on auth response before accessing token property.",
                            Solution = "",
                            Sprint = "May 2026",
                            State = "Active",
                            StepsToReproduce = "1. Open /login\n2. Enter wrong password\n3. Click Submit",
                            Title = "Login page crashes on invalid credentials",
                            UnitTest = "Add test: should display error message when credentials are invalid.",
                            WorkItemNumber = 2,
                            WorkItemType = "Bug"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000003"),
                            AssignedToId = new Guid("00000000-0000-0000-0001-000000000002"),
                            CompletedWork = 1.5m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomFieldsJson = "{}",
                            Description = "Cover LoginAsync, RefreshTokenAsync, and RevokeTokenAsync with xUnit + Moq.",
                            DesignReview = "",
                            IsDeleted = false,
                            Links = "[]",
                            OriginalEstimate = 4m,
                            Priority = "Medium",
                            RemainingWork = 2.5m,
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001"),
                            Sprint = "May 2026",
                            State = "Active",
                            Title = "Write unit tests for AuthService",
                            UnitTest = "Cover LoginAsync, RefreshTokenAsync, RevokeTokenAsync — aim for 100% branch coverage.",
                            WorkItemNumber = 3,
                            WorkItemType = "Task"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomFieldsJson = "{}",
                            Description = "Show an in-app notification 5 minutes before the session expires so users can renew without losing their work.",
                            IsDeleted = false,
                            Links = "[]",
                            Priority = "Low",
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001"),
                            Sprint = "May 2026",
                            State = "New",
                            Title = "Improve JWT refresh token expiry UX",
                            WorkItemNumber = 4,
                            WorkItemType = "Improvement"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000005"),
                            AssignedToId = new Guid("00000000-0000-0000-0001-000000000001"),
                            Automated = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomFieldsJson = "{}",
                            Description = "Validate the full authentication flow across major browsers: Chrome, Firefox, Edge.",
                            IsDeleted = false,
                            Links = "[]",
                            Priority = "Medium",
                            RepositoryId = new Guid("00000000-0000-0000-0002-000000000001"),
                            Sprint = "May 2026",
                            State = "Design",
                            TestSteps = "[\"Open /login in Chrome, Firefox, and Edge.\",\"Enter valid credentials and submit.\",\"Verify redirect to /overview and JWT stored in localStorage.\",\"Enter invalid credentials and submit.\",\"Verify error message is displayed without crash.\",\"Let session expire; verify refresh token renews silently.\"]",
                            Title = "End-to-end login flow test plan",
                            WorkItemNumber = 5,
                            WorkItemType = "TestPlan"
                        });
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.BacklogItem", b =>
                {
                    b.HasOne("DASHBOARD.Domain.Entities.BacklogItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.CapacityMember", b =>
                {
                    b.HasOne("DASHBOARD.Domain.Entities.Sprint", "Sprint")
                        .WithMany("CapacityMembers")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DASHBOARD.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sprint");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.CustomRole", b =>
                {
                    b.HasOne("DASHBOARD.Domain.Entities.Repository", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.DayOff", b =>
                {
                    b.HasOne("DASHBOARD.Domain.Entities.Sprint", "Sprint")
                        .WithMany("DaysOff")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DASHBOARD.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Sprint");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.DiscussionEntry", b =>
                {
                    b.HasOne("DASHBOARD.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DASHBOARD.Domain.Entities.WorkItem", "WorkItem")
                        .WithMany("Discussions")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.HistoryEntry", b =>
                {
                    b.HasOne("DASHBOARD.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DASHBOARD.Domain.Entities.WorkItem", "WorkItem")
                        .WithMany("History")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.Invitation", b =>
                {
                    b.HasOne("DASHBOARD.Domain.Entities.User", "InvitedBy")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DASHBOARD.Domain.Entities.Repository", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvitedBy");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.RepositoryMember", b =>
                {
                    b.HasOne("DASHBOARD.Domain.Entities.CustomRole", "CustomRole")
                        .WithMany()
                        .HasForeignKey("CustomRoleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DASHBOARD.Domain.Entities.Repository", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DASHBOARD.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomRole");

                    b.Navigation("Repository");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.RepositoryMetadata", b =>
                {
                    b.HasOne("DASHBOARD.Domain.Entities.Repository", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.SmartBoardCard", b =>
                {
                    b.HasOne("DASHBOARD.Domain.Entities.SmartBoardColumn", "Column")
                        .WithMany("Cards")
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DASHBOARD.Domain.Entities.WorkItem", "WorkItem")
                        .WithMany()
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Column");

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.SprintTask", b =>
                {
                    b.HasOne("DASHBOARD.Domain.Entities.User", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DASHBOARD.Domain.Entities.BacklogItem", "BacklogItem")
                        .WithMany()
                        .HasForeignKey("BacklogItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DASHBOARD.Domain.Entities.SprintTask", "Parent")
                        .WithMany("SubTasks")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DASHBOARD.Domain.Entities.Sprint", "Sprint")
                        .WithMany("Tasks")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("BacklogItem");

                    b.Navigation("Parent");

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.User", b =>
                {
                    b.HasOne("DASHBOARD.Domain.Entities.User", "Manager")
                        .WithMany("Subordinates")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.UserToken", b =>
                {
                    b.HasOne("DASHBOARD.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.WikiPage", b =>
                {
                    b.HasOne("DASHBOARD.Domain.Entities.WikiPage", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.WorkItem", b =>
                {
                    b.HasOne("DASHBOARD.Domain.Entities.User", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DASHBOARD.Domain.Entities.Repository", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.BacklogItem", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.SmartBoardColumn", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.Sprint", b =>
                {
                    b.Navigation("CapacityMembers");

                    b.Navigation("DaysOff");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.SprintTask", b =>
                {
                    b.Navigation("SubTasks");
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.User", b =>
                {
                    b.Navigation("Subordinates");
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.WikiPage", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("DASHBOARD.Domain.Entities.WorkItem", b =>
                {
                    b.Navigation("Discussions");

                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
